### ISSUE TITLE
【BUG】不能演习

### ISSUE THREAD

**Issue by hyartintel** [gwy15/HmNewUISucks#2]
点演习会闪退（在获取演习对象列表的这一步）

**Comment by gwy15** [comment]
@hyartintel 可能是拉取的列表里面有新船。下午六点之后的演习还闪退吗？

**Comment by hyartintel** [comment]
> @hyartintel 可能是拉取的列表里面有新船。下午六点之后的演习还闪退吗？

不闪退了
